### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Play2KillTV** [jackthehack21/koth#12]
Can you make it time based? Like at a certain time the koth arena will be enabled so players can join and then after the koth ends you need to wait another amount of time for koth to be activated again.

**Comment by jackthehack21** [comment]
There isn’t much point in me adding that when plugins like TimeCommander can make use of the commands and do exactly that.

**Comment by jackthehack21** [comment]
But regarding ‘disabling’ a arena to stop players entering that I may add, but plugins using the API can override it.

**Comment by Play2KillTV** [comment]
Thats the one that I am asking but I can't explain it. Because players can
start up koth on their own. What I am asking os for a plugin like "time
commander" to enable joining the koth and then disabling it at the end
of the game.

**Comment by jackthehack21** [comment]
The issue with that is because of the logic of plugin it won’t start if no ones in there, I’ll add a option to disable/enable a arena and the rest TimeCommander is something else can do the rest, no point in me adding it.

**Comment by Play2KillTV** [comment]
Yes ok I know what to do. I will enable the arena then message the players
to join. Then after the game ends I will disable the arena again.

**Comment by jackthehack21** [comment]
Added enable/disable arena's in Beta4.
