### ISSUE TITLE
[Bug Report] IssueNameHere

### ISSUE THREAD

**Issue by mikeygio10** [jackthehack21/koth#13]
**Describe the bug in detail**
A clear and in depth description of the bug.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'after server reset it removes the arenas spawn points'
3. Server crash
etc.

**Expected behaviour**

**Actual behaviour**
What actually happens.

**Screenshots**
Add screenshots to help explain your problem.

**Host (please complete the following information):**
 - OS: [e.g. Windows10]
 - PocketMine Version: [e.g. 3.9.0]
 - Plugin Version [e.g. 1.0.0-Beta3]

**Player Device (If applicable | please complete the following information):**
 - OS: [e.g. iOS12.1]
 - MCPE Version [e.g. 1.12.0]

**Server Log (IMPORTANT)**
Please have both pmmp's debug option set to '2' and koth's debug option enabled.
Please paste your server.log content using https://pastebin.com

**Additional context/notes**
Add any other context/notes about the problem here.

**Comment by jackthehack21** [comment]
Invalid issue, template not followed.
