### ISSUE TITLE
Case sensitive replacement values.

### ISSUE THREAD

**Issue by Dqfault** [jackthehack21/koth#31]
I've found an issue involving the KOTH rewards. I set the reward as "givemoney {player} (amount), but it says "player {player} was never connected. How can I give the KOTH winner money?

**Comment by JaxkDev** [comment]
You have to use {PLAYER} not {player} character case is assumed all uppercase although i admit i should change that to be either lower/upper case.

**Comment by JaxkDev** [comment]
Keeping it uppercase only to make it clear in messages that they are variables.
