### ISSUE TITLE
Error on server startup.

### ISSUE THREAD

**Issue by Coot302** [jackthehack21/koth#35]
18:57:41.997] [Server thread/CRITICAL]: Exception: "Cannot be run from source." (EXCEPTION) in "plugins/koth-stable/src/Main" at line 73
--- Stack trace ---
  #0 pmsrc/src/plugin/PluginBase(75): JaxkDev\KOTH\Main->onLoad()
  #1 pmsrc/src/plugin/PluginManager(213): pocketmine\plugin\PluginBase->construct(object DevTools\FolderPluginLoader#26249, object pocketmine\Server#10, object pocketmine\plugin\PluginDescription#26314, string[28] /home/container/plugins/KOTH, string[35] /home/container/plugins/koth-stable, object pocketmine\plugin\DiskResourceProvider#26831)
  #2 pmsrc/src/plugin/PluginManager(362): pocketmine\plugin\PluginManager->internalLoadPlugin(string[35] /home/container/plugins/koth-stable, object DevTools\FolderPluginLoader#26249, object pocketmine\plugin\PluginDescription#26314)
  #3 pmsrc/src/Server(1007): pocketmine\plugin\PluginManager->loadPlugins(string[24] /home/container/plugins/, int 0)
  #4 pmsrc/src/PocketMine(304): pocketmine\Server->construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #5 pmsrc/src/PocketMine(327): pocketmine\server()
  #6 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---

**Comment by JaxkDev** [comment]
Says it very clearly, cannot be run from source.

No support for development/modified versions / source.

**Comment by ErosionYT** [comment]
u could just remove `        if(Phar::running() === ""){
            throw new Exception("Cannot be run from source.");
        }
`

and it should work
