### ISSUE TITLE
[Bug Report] Class not found

### ISSUE THREAD

**Issue by ErosionYT** [jackthehack21/koth#37]
**To Reproduce**
1. Download the plugin off poggit (dev # 15)
2. Place in server and restart

**Expected behaviour**
The plugin to load

**Actual behaviour**
Plugin crashes because of class not found

**Host (please complete the following information):**
 - OS: WIN10
 - PocketMine Version: 4.7.0
 - Plugin Version DEV # 15

**Player Device (If applicable | please complete the following information):**
 - OS: [e.g. iOS12.1]
 - MCPE Version [e.g. 1.12.0]

**Server Log (IMPORTANT)**
Error: "Class "JaxkDev\KOTH\libs\poggit\libasynql\libasynql" not found" (EXCEPTION) in "plugins/KOTH_dev-15.phar/src/Providers/SqlProvider" at line 50

**Comment by JaxkDev** [comment]
No support for non-releases

**Comment by ErosionYT** [comment]
i have fixed it myself lmfao, just letting u know it doesnt work

**Comment by JaxkDev** [comment]
It’s not a plugin issue by design it does work
