### ISSUE TITLE
[Bug Report] IssueNameHere

### ISSUE THREAD

**Issue by YT-Duckyyy** [jackthehack21/koth#38]
**Describe the bug in detail**
On startup, server crashes

**To Reproduce**
Steps to reproduce the behaviour:
Add Plugin
Start Server

**Expected behaviour**
Run Smoothly

**Actual behaviour**
Crashes

**Screenshots**~
Heres the error:
[16:41:18.952] [Server thread/CRITICAL]: Error: "Class "poggit\libasynql\libasynql" not found" (EXCEPTION) in "plugins/koth.phar/src/Providers/SqlProvider" at line 50
--- Stack trace ---
  #0 plugins/koth.phar/src/Main(64): JaxkDev\KOTH\Providers\SqlProvider->open(object Closure#105878)
  #1 plugins/koth.phar/src/Main(125): JaxkDev\KOTH\Main->loadArenas()
  #2 pmsrc/src/plugin/PluginBase(117): JaxkDev\KOTH\Main->onEnable()
  #3 pmsrc/src/plugin/PluginManager(448): pocketmine\plugin\PluginBase->onEnableStateChange(true)
  #4 pmsrc/src/Server(1419): pocketmine\plugin\PluginManager->enablePlugin(object JaxkDev\KOTH\Main#101289)
  #5 pmsrc/src/Server(1024): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#21903)
  #6 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #7 pmsrc/src/PocketMine(327): pocketmine\server()
  #8 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---

**Host (please complete the following information):**
 - OS: [e.g. Windows10] 
 - PocketMine Version: [e.g. 3.9.0] Latest
 - Plugin Version [e.g. 1.0.0-Beta3] Latest

**Player Device (If applicable | please complete the following information):**
 - Device: [e.g. iPhone6] Windows10 PC
 - OS: [e.g. iOS12.1] Windows10
 - MCPE Version [e.g. 1.12.0] Latest

**Server Log (IMPORTANT)**
Please have both pmmp's debug option set to '2' and koth's debug option enabled.
Please paste your server.log content using https://pastebin.com

**Additional context/notes**
Add any other context/notes about the problem here.

**Comment by YT-Duckyyy** [comment]
I have the virion in the virion folder, however still crashes because its not found

**Comment by YT-Duckyyy** [comment]
![image](https://user-images.githubusercontent.com/97541939/185801884-5624e6ac-6769-4da3-b94b-2d39903673fd.png)

**Comment by JaxkDev** [comment]
Use of unreleased versions are completely your responsibility and I provide no support.

**Comment by YT-Duckyyy** [comment]
> Use of unreleased versions are completely your responsibility and I provide no support.

Is it a bug or something my side
