### ISSUE TITLE
[Issue] FloatingText Creation error.

### ISSUE THREAD

**Issue by XxCreditIsGoodXx** [jackthehack21/koth#6]
2019-05-03 [16:06:24] [Server thread/CRITICAL]: TypeError: "Argument 2 passed to Jackthehack21\KOTH\FloatingText::__construct() must be an instance of pocketmine\level\Level, null given, called in phar:///aternos/server/plugins/KOTH.phar/src/Jackthehack21/KOTH/Arena.php on line 215" (EXCEPTION) in "plugins/KOTH.phar/src/Jackthehack21/KOTH/FloatingText" at line 45
--
706 | 2019-05-03 [16:06:24] [Server thread/DEBUG]: #0 plugins/KOTH.phar/src/Jackthehack21/KOTH/Arena(215): Jackthehack21\KOTH\FloatingText-&gt;__construct(Jackthehack21\KOTH\Main object, NULL , pocketmine\math\Vector3 object, string ..cKing: ..6-)
707 | 2019-05-03 [16:06:24] [Server thread/DEBUG]: #1 plugins/KOTH.phar/src/Jackthehack21/KOTH/Arena(327): Jackthehack21\KOTH\Arena-&gt;createKingTextParticle()
708 | 2019-05-03 [16:06:24] [Server thread/DEBUG]: #2 plugins/KOTH.phar/src/Jackthehack21/KOTH/Tasks/Prestart(64): Jackthehack21\KOTH\Arena-&gt;startGame()
709 | 2019-05-03 [16:06:24] [Server thread/DEBUG]: #3 src/pocketmine/scheduler/TaskHandler(159): Jackthehack21\KOTH\Tasks\Prestart-&gt;onRun(integer 64159)
710 | 2019-05-03 [16:06:24] [Server thread/DEBUG]: #4 src/pocketmine/scheduler/TaskScheduler(199): pocketmine\scheduler\TaskHandler-&gt;run(integer 64159)
711 | 2019-05-03 [16:06:24] [Server thread/DEBUG]: #5 src/pocketmine/plugin/PluginManager(688): pocketmine\scheduler\TaskScheduler-&gt;mainThreadHeartbeat(integer 64159)
712 | 2019-05-03 [16:06:24] [Server thread/DEBUG]: #6 src/pocketmine/Server(2559): pocketmine\plugin\PluginManager-&gt;tickSchedulers(integer 64159)
713 | 2019-05-03 [16:06:24] [Server thread/DEBUG]: #7 src/pocketmine/Server(2335): pocketmine\Server-&gt;tick()
714 | 2019-05-03 [16:06:24] [Server thread/DEBUG]: #8 src/pocketmine/Server(2196): pocketmine\Server-&gt;tickProcessor()
715 | 2019-05-03 [16:06:24] [Server thread/DEBUG]: #9 src/pocketmine/Server(1775): pocketmine\Server-&gt;start()
716 | 2019-05-03 [16:06:24] [Server thread/DEBUG]: #10 src/pocketmine/PocketMine(258): pocketmine\Server-&gt;__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /aternos/server/, string /aternos/server/plugins/)
717 | 2019-05-03 [16:06:24] [Server thread/DEBUG]: #11 (1): require(string phar:///aternos/server/server.phar/src/pocketmine/PocketMine.php)
718 | 2019-05-03 [16:06:24] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
719 | 2019-05-03 [16:06:24] [Server thread/EMERGENCY]: Please upload the "/aternos/server/crashdumps/Fri_May_3-16.06.24-EDT_2019.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
720 | 2019-05-03 [16:06:24] [Server thread/EMERGENCY]: The crash dump has been automatically submitted to the Crash Archive. You can view it on https://crash.pmmp.io/view/2362103 or use the ID #2362103.

Any idea for fix

**Comment by jackthehack21** [comment]
Your the first and only person to get that, please leave your server version, plugin version/build, and your arenas.yml file.

**Comment by XxCreditIsGoodXx** [comment]
wdym

**Comment by jackthehack21** [comment]
do /ver and /plugins and say what server version your on and what plugin version
and send the content of arenas.yml (from plugin_data/KOTH/)

**Comment by XxCreditIsGoodXx** [comment]
Verison is 1.8.1 and hold up for plugins

**Comment by jackthehack21** [comment]
@XxCreditIsGoodXx i need the file to be able to trace your error further, as your version does not have a fully functional debug right now.

**Comment by XxCreditIsGoodXx** [comment]
The arena file

**Comment by jackthehack21** [comment]
Yes

**Comment by XxCreditIsGoodXx** [comment]
The thing is the server crashes and then it clears my arena. So the arena.yml is empty

**Comment by jackthehack21** [comment]
It wouldn’t, unless it crashed during saving. 
And it doesn’t

**Comment by jackthehack21** [comment]
Can’t find cause, failed to replicate.

**Comment by XxCreditIsGoodXx** [comment]
I will test this plugin again using a different worlds plugin

**Comment by jackthehack21** [comment]
Confirmed finally after some digging, somehow you manage to bypass my status check when a world is deleted and so the particle fails to create, fixed in Beta3.
