### ISSUE TITLE
Corrupt Arena

### ISSUE THREAD

**Issue by LoloD22NR** [jackthehack21/koth#7]
Hy when i want to start à game with /hoth join : the Arena is corrupt
Please help me

**Comment by jackthehack21** [comment]
Please provide the following info:
- plugin version/build
- server version
- arenas.yml or the SQLite file.
- list of server worlds.

**Comment by jackthehack21** [comment]
At this time it only shows that message if the arena is setup in a world that does not exist anymore.

**Comment by LoloD22NR** [comment]
Thanks ! Juste change World and its good

**Comment by jackthehack21** [comment]
Good to know it works though, it’s better to display a corrupt message then crashing servers 😅
