### ISSUE TITLE
Can’t start KOTH game from console.

### ISSUE THREAD

**Issue by xDanub** [jackthehack21/koth#8]
Please fix this because I want to run a KOTH game from console 🍡

**Comment by DenielWorld** [comment]
Well if it won't cause any errors u could make a fork removing the check for if you are running command from console.

**Comment by jackthehack21** [comment]
It could case errors if you remove it completely.
I will allow certain commands to be used via console in the next update.
If you don’t want to wait (it may be a long time) use the source code in dev branch the next commit will add console support.

**Comment by jackthehack21** [comment]
Added in beta4
