### ISSUE TITLE
Invalid Setup.

### ISSUE THREAD

**Issue by ZandercraftGames** [jackthehack21/koth#9]
I have fully configured the world, yet it says that its configuration is invalid. When I click on a sign from KOTH-Signs, it tells me that the world no longer exists. I can assure you, this world does exist and is even spelt correctly in the DB entry. 
![20190727_191223](https://user-images.githubusercontent.com/28664144/62000355-c05cab80-b0a2-11e9-812d-a9ff05643c3c.jpg)

**Comment by ZandercraftGames** [comment]
And I dont know why it has no rewards setup on the DB because there are rewards listed when I do the /koth info KingOfTheHill command.

**Comment by jackthehack21** [comment]
That’s outdated data.

**Comment by jackthehack21** [comment]
Can you check the worlds * folder name* and send it exactly here (case-specific)

**Comment by ZandercraftGames** [comment]
KingOfTheHill

**Comment by jackthehack21** [comment]
Please try using that case specific in the name section

**Comment by ZandercraftGames** [comment]
Okay, will do. Just a little busy right now. I will get back to you on if it works.

**Comment by jackthehack21** [comment]
Anything @ZandercraftGames ?

**Comment by jackthehack21** [comment]
Unable to replicate it but i have changed somethings to world verification and other things latest commit should fix anything happening via plugin but i cannot do much without me being able to replicate it.

**Comment by Play2KillTV** [comment]
Ok thank you and sorry for me asking a lot. Sorry again If I cannot reply
to the conversation because it is night time here.

**Comment by jackthehack21** [comment]
The only way i could reproduce this was have the world the arena is in unloaded.
looking into it.

**Comment by jackthehack21** [comment]
Beta4 will attempt to load the world on load, now has invalid setup when world doesnt exist at all.

**Comment by Play2KillTV** [comment]
So I need a world manager for this?

**Comment by jackthehack21** [comment]
What ?
If you weren’t using one you dont need to now.

**Comment by Play2KillTV** [comment]
Ok and Happy Friendship Day!
